### PR TITLE
Behaviour Trees

### PR DESCRIPTION
**Pull request by SebastianMeinberger**
Adds Behaviour Trees as new option to execute tasks on an agent.  In order to make it easy and consistent to use a behaviour trees on an agent instead of the existing scheduling based approach, I abstracted the execution of task with an Interface called ITaskSystem, which is implemented by both the scheduling based approach and the behaviour tree approach.

Behaviour Trees are implemented using interfaces based on the existing IAgentTAsk interface. This allows them to use all existing AgentTasks seamlessly. Currently, only a small set of nodes is implemented, i.e. Sequencer Nodes and Selector Nodes.
The current tasks were altered slightly, since the Behaviour Tree Implmentation now offers the possibility for tasks to fail. This is for example handy for the Movement Task, which now fails, when the NavmeshAgent can't find a route to its destination. Additionally, tasks now no longer indicate if they are finished trough an event, but trough returning a taskstate when updated. 

Also adds a visual behaviour tree editor.  It allows to create behavior trees more comfortbaly and to save them persitently in an asset. The options for manipulating nodes are however currently on as minimal as it is possible. It offers no quality of life things like undo/redo, cutout, copypaste or similar things. Additionaly, the execution order of children and which node is the root node curretly depends completly on the order in which they were added to the tree. This is all reduces the usabilty, but keeps the implementation relativly simple for a first small release.
If a behavior tree is created using this editor, only tasks that implement the new ISerializable interface can be used, since a custome serializer was needed in order to save a tree abstracted by interfaces in an asset (Unitys default serialization does not work for interface types).

grafik

In order to use the editor, it has be opened trough Unitys top toolbar "i5 Toolkit>BehaviourTreeEditor".
grafik
When opend, it will prompt the user to select a tree from the project window.
grafik
Now, you can either select an existing tree, in exaple the SampleTree from the Behaviour Tree Sample Scene, or create one by rightclicking in the project window and selecting "Create>i5 Toolkit>Behaviour Tree".
grafik
To add nodes to the tree, rightclick onto the grid and select the desired node.

A working tree created with the Behaviour Tree Editor is displayed in the BehaviourTreeSampleScene. Here, the agent will try to move to Waypoint 1, but if it can't reach it, it goes to Waypoint 2 instead. This is done two times, the first time they way to Waypoint 1 is blocked and the second time, it isn't.

### CODE REVIEW

**Comment by BenediktHensen** [comment]
Currently, if I load the project, I get the following compiler errors:

grafik

They seem to be caused by the method implementations in the interface. I think we should avoid them as they restrict the language level that we can work with to C# 8 and we do not really want to force users of the toolkit to switch to a specific runtime/language version if not absolutely necessary. Instead, such method implementations could be put into the AgentBaseTask class.

Could you also take a look at the merge conflicts that this pull request has?

**Comment by SebastianMeinberger** [comment]
> Currently, if I load the project, I get the following compiler errors:
> 
> They seem to be caused by the method implementations in the interface. I think we should avoid them as they restrict the language level that we can work with to C# 8 and we do not really want to force users of the toolkit to switch to a specific runtime/language version if not absolutely necessary. Instead, such method implementations could be put into the AgentBaseTask class.
> 
> Could you also take a look at the merge conflicts that this pull request has?

I resolved the merge conflicts (sorry for that, I forgot to fetch the upstream on the fork) and moved the default interface implementations into the new class BaseTask which is like the AgentBaseTask class, but also for tasks not concerning the agent directly (i.e. Decorator and Composite nodes currently)

**Comment by BenediktHensen** [comment]
Ok, thank you!

There is now one compilation error left. Can you take a look at it? The PopulateView method of the BehaviourTreeView calls the GraphView's DeleteElements method and passes to it the graphElements but apparently, it cannot convert them to IEnumerable. Might this be an issue with the package version of the UIElements?

```
Assets\Virtual Agents Framework\Editor\Scripts\Behaviour Tree\BehaviourTreeView.cs(48,28): error CS1503: Argument 1: cannot convert from 'UnityEngine.UIElements.UQueryState<UnityEditor.Experimental.GraphView.GraphElement>' to 'System.Collections.Generic.IEnumerable<UnityEditor.Experimental.GraphView.GraphElement>'
```

**Comment by SebastianMeinberger** [comment]
I was not able to replicate the error, but I suspect that in in older Unity Versions, UQueryState does not implement IEnumerable. I converted the UQueryState variable into a list (which obviously does implement IEnumerable), which according to the API documentation should be supported in every Unity Version that inlcudes the UQueryState class.
I hope this fixes the error.

**Comment by BenediktHensen** [comment]
Perfect, now it works.

One consideration regarding the architecture is that we should find another way to define the task system for the Agent class. Currently, if we want to add a new task system, we would always need to touch the Agent class and extend the switch and enum with a new entry. It also adds inspector fields which are only used in one of the task systems but not the others (like the field where you can drag and drop the behavior tree). I think we could instead extract the different task system classes into separate components. So one component is a TaskQueue component and one is a BehaviorTree component. The agent class then just searches for this task system component in the beginning and depending on what it finds, it acts differently.

This component solution should also solve how the ITaskSystem interface is implemented. Currently, the two scheduling methods only have the Update method in common but the scheduling method is only needed by the queue system. On the behavior tree, the interface mandates it but it does not make sense for the tree and so it throws an intended exception. We should remove the ScheduleTask method from the interface and instead make it specific to the task queue system.

To make this work, we need to do something with the current ScheduleTask and task shortcuts on the Agent class as they currently pipe their input into the task system. This would not work anymore if the TaskSystem interface does not define the ScheduleTask method anymore. However, since this method and the shortcuts are only syntactic sugar, we could completely remove them and let developers directly interact with the task system component, e.g., with the task queue component to. I think a more conventient solution would be to move them from the Agent class into a child class TaskQueueAgent. With this class, the methods and shortcuts still exist and it checks in the beginning that its TaskSystem component is a task queue.

**Comment by SebastianMeinberger** [comment]
The TaskSystems are now monobehaviours, inherting the TaskSystem Monobehaviour and the ITaskSystem interface. I removed the ScheduleTask method from the ITaskSystem. To schedule tasks, controllers now have to communicate with the Schedule based tasksystem directly. The Tasks class for the shortcuts is now also in the Schedule Task system and no longer in the agent.  The agent script will now search for any component attached to its gameobject that inherits the TaskSystem Script, therefore it no longer requires any alteration if new TaskSystems are added. I also was able to delete the tasksystem enum and the agent doesn't feature an inspector field that is only reqired for one task system.

I also added an explicite agent for working with the schedule based system and one for working with the behaviour trees. These enforce an Schedule/BehaviourTree component via the RequireComponent tag. The general agent only throws a warning if no TaskSystem component is attached, since enforcing a tasksystem there is not possible (If the parent class TaskSystem is enforced, an agent will automatically get a component that implemenets no own functionallity, that can not easily be deleted and that can be confused with the actual task system. If one of its implementations is enforced, it is harder to use one of the other implemetations.)

**Review by BenediktHensen — APPROVED** [review]
Brilliant work! Thank you!

I made a minor change in renaming the methods of the ITask interface, in particular the Execute, Update and FullUpdate methods so that their names better reflect what they are doing. Since Execute is has become the method that is called to begin the task, it is now called StartExecution. For the Update and FullUpdate methods, they should definitely be distinguished in their naming. The Update methods all seem to be more focused on getting the current state of the task, so I renamed it to EvaluateTaskState. The FullUpdate method seems to be the one driving the execution of the task by automatically starting, updating and stopping it. Hence, I renamed it to Tick to resemble the tick-based evaluation of the trees.

One other change I made was to remove the child classes of the Agent again as they are not needed. We can keep the core Agent component on the agent's gameobject and can switch out the task system by attaching the corresponding task system component. The agent class itself is unaffected by this and just fetches the task system that it finds. So, developers who switch between task systems, do not need to touch the Agent component.

**Pull request merged**
